"""empty message

Revision ID: 6c67ed1d66ae
Revises: 1797cef2cd31
Create Date: 2019-12-05 19:46:21.979595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c67ed1d66ae'
down_revision = '1797cef2cd31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('b_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'books', 'users', ['b_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_column('books', 'b_user_id')
    # ### end Alembic commands ###
