"""empty message

Revision ID: 743dafb878fb
Revises: 
Create Date: 2019-12-05 19:41:25.974460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '743dafb878fb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('b_name', sa.String(length=32), nullable=False),
    sa.Column('b_author', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('books')
    # ### end Alembic commands ###
